//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemporalMigracion
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public string CedulaNit { get; set; }
        public string Telefono { get; set; }
        public string Direccion { get; set; }
        public int LimiteCredito { get; set; }
        public byte IdEstado { get; set; }
        public short IdUsuarioCreador { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<short> IdUsuarioModificador { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    }
}
