//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemporalMigracion
{
    using System;
    using System.Collections.Generic;
    
    public partial class CodigosDeBarraProductos
    {
        public int IdProducto { get; set; }
        public string Codigo { get; set; }
    }
}
