//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemporalMigracion
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class POS_V1Entities : DbContext
    {
        public POS_V1Entities()
            : base("name=POS_V1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Caja> Caja { get; set; }
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<CodigosDeBarraProductos> CodigosDeBarraProductos { get; set; }
        public virtual DbSet<Deuda> Deuda { get; set; }
        public virtual DbSet<ProductoProveedor> ProductoProveedor { get; set; }
        public virtual DbSet<Productos> Productos { get; set; }
        public virtual DbSet<Proveedores> Proveedores { get; set; }
        public virtual DbSet<UbicacionBodega> UbicacionBodega { get; set; }
        public virtual DbSet<UbicacionStock> UbicacionStock { get; set; }
        public virtual DbSet<Ventas> Ventas { get; set; }
    }
}
