//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemporalMigracion
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proveedores
    {
        public short Id { get; set; }
        public string Nombre { get; set; }
        public bool VisitaLunes { get; set; }
        public bool VisitaMartes { get; set; }
        public bool VisitaMiercoles { get; set; }
        public bool VisitaJueves { get; set; }
        public bool VisitaViernes { get; set; }
        public bool VisitaSabado { get; set; }
        public bool VisitaDomingo { get; set; }
        public bool EntregaLunes { get; set; }
        public bool EntregaMartes { get; set; }
        public bool EntregaMiercoles { get; set; }
        public bool EntregaJueves { get; set; }
        public bool EntregaViernes { get; set; }
        public bool EntregaSabado { get; set; }
        public bool EntregaDomingo { get; set; }
        public byte IdEstado { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public short IdUsuarioRegistro { get; set; }
        public Nullable<System.DateTime> FechaModificado { get; set; }
        public Nullable<short> IdUsuarioModificador { get; set; }
    }
}
