//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemporalMigracion
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ventas
    {
        public int IdProducto { get; set; }
        public byte Cantidad { get; set; }
        public short IdCliente { get; set; }
        public int Total { get; set; }
        public short IdVendedor { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public int IdVenta { get; set; }
    }
}
