//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoUstaDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogPedidosProyectoUsta
    {
        public int Id { get; set; }
        public short IdProveedor { get; set; }
        public string Observaciones { get; set; }
        public System.DateTime FechaReferencia { get; set; }
        public int ValorPedido { get; set; }
        public int IdUsuarioRegistro { get; set; }
        public System.DateTime FechaRegistro { get; set; }
    }
}
