//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoUstaDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductosBufferAInventarioProyectoUsta
    {
        public int Id { get; set; }
        public int IdProducto { get; set; }
        public short IdProveedor { get; set; }
        public short QtyPedida { get; set; }
        public short QtyRealAIngresar { get; set; }
        public int CostoItem { get; set; }
        public int PrecioAsignado { get; set; }
        public int IdUsuarioRegistro { get; set; }
        public Nullable<System.DateTime> FechaReferencia { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public Nullable<int> IdUsuarioModificado { get; set; }
        public Nullable<System.DateTime> FechaModificado { get; set; }
    }
}
