//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoUstaDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProveedoresProyectoUsta
    {
        public short Id { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public string Nit { get; set; }
        public Nullable<int> Telefono { get; set; }
        public bool Visita_Lunes { get; set; }
        public bool Visita_Martes { get; set; }
        public bool Visita_Miercoles { get; set; }
        public bool Visita_Jueves { get; set; }
        public bool Visita_Viernes { get; set; }
        public bool Visita_Sabado { get; set; }
        public bool Visita_Domingo { get; set; }
        public bool Entrega_Lunes { get; set; }
        public bool Entrega_Martes { get; set; }
        public bool Entrega_Miercoles { get; set; }
        public bool Entrega_Jueves { get; set; }
        public bool Entrega_Viernes { get; set; }
        public bool Entrega_Sabado { get; set; }
        public bool Entrega_Domingo { get; set; }
        public bool IdEstado { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public int IdUsuarioCreador { get; set; }
        public Nullable<System.DateTime> FechaModificado { get; set; }
        public Nullable<int> IdUsuarioModificador { get; set; }
    }
}
