//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoUstaDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class VentasProyectoUsta
    {
        public int IdProducto { get; set; }
        public short Cantidad { get; set; }
        public short IdCliente { get; set; }
        public int IdVendedor { get; set; }
        public int Total { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public int Id { get; set; }
    }
}
