//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoGradoUstaSecurity
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolesProyectoUsta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RolesProyectoUsta()
        {
            this.UsuariosRolesProyectoUsta = new HashSet<UsuariosRolesProyectoUsta>();
        }
    
        public short IdRol { get; set; }
        public string NombreRol { get; set; }
        public bool IdEstado { get; set; }
        public int IdUsuarioCreador { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public Nullable<int> IdUsuarioModificador { get; set; }
        public Nullable<System.DateTime> FechaModificado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsuariosRolesProyectoUsta> UsuariosRolesProyectoUsta { get; set; }
    }
}
