//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoGradoUstaSecurity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProyectoUstaEntities : DbContext
    {
        public ProyectoUstaEntities()
            : base("name=ProyectoUstaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<UsuariosProyectoUsta> UsuariosProyectoUsta { get; set; }
        public virtual DbSet<IdiomasProyectoUsta> IdiomasProyectoUsta { get; set; }
        public virtual DbSet<OpcionesProyectoUsta> OpcionesProyectoUsta { get; set; }
        public virtual DbSet<OpcionesUsuarioProyectoUsta> OpcionesUsuarioProyectoUsta { get; set; }
        public virtual DbSet<RolesProyectoUsta> RolesProyectoUsta { get; set; }
        public virtual DbSet<TipoOpcionMenuProyectoUsta> TipoOpcionMenuProyectoUsta { get; set; }
        public virtual DbSet<UsuariosRolesProyectoUsta> UsuariosRolesProyectoUsta { get; set; }
        public virtual DbSet<OpcionesRolProyectoUsta> OpcionesRolProyectoUsta { get; set; }
    }
}
