//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoGradoUstaSecurity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuariosRolesProyectoUsta
    {
        public int IdUsuario { get; set; }
        public short IdRol { get; set; }
        public bool MenuEspecifico { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public int IdUsuarioRegistro { get; set; }
    
        public virtual UsuariosProyectoUsta UsuariosProyectoUsta { get; set; }
        public virtual RolesProyectoUsta RolesProyectoUsta { get; set; }
    }
}
